// <auto-generated />
using System;
using ConferenceAttendees.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceAttendees.Api.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    [Migration("20251204230436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConferenceAttendees.Api.Data.Models.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<Guid?>("ReferralSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("ReferralSourceId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("ConferenceAttendees.Api.Data.Models.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("995dd6e5-6a17-4f7d-9e61-7563ce443317"),
                            Name = "Male"
                        },
                        new
                        {
                            Id = new Guid("bef000a6-0b2e-4ae9-9202-4afadc772b68"),
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("ConferenceAttendees.Api.Data.Models.JobRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdf05908-cb76-4bfc-870f-0b549d2ee80e"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("b441ab89-404a-406e-8915-04ef7e1a2ab4"),
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = new Guid("e950a843-bfd2-4c0c-bf27-a5d338600b3c"),
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("ConferenceAttendees.Api.Data.Models.ReferralSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReferralSources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45ed833d-6954-4b54-b6c0-8e5b3817ac8f"),
                            Name = "Internet Advertisement"
                        },
                        new
                        {
                            Id = new Guid("5d951b9e-d7cd-4914-b7fd-5f44b42dfe9f"),
                            Name = "Television"
                        },
                        new
                        {
                            Id = new Guid("a9bc3e61-de20-44bf-b834-e21e035ae706"),
                            Name = "Newspaper Article"
                        });
                });

            modelBuilder.Entity("ConferenceAttendees.Api.Data.Models.Attendee", b =>
                {
                    b.HasOne("ConferenceAttendees.Api.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("ConferenceAttendees.Api.Data.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId");

                    b.HasOne("ConferenceAttendees.Api.Data.Models.ReferralSource", "ReferralSource")
                        .WithMany()
                        .HasForeignKey("ReferralSourceId");

                    b.Navigation("Gender");

                    b.Navigation("JobRole");

                    b.Navigation("ReferralSource");
                });
#pragma warning restore 612, 618
        }
    }
}
